import os

STAGE = os.getenv("STAGE", "LOCAL")
FILE_ROOT = os.getenv("FILE_ROOT", '_db/')

_BANK_ACCOUNT_TABLE_ID = os.getenv("BANK_ACCOUNT_TABLE_ID", "bank_account_table")
_BANK_TRANSACTION_TABLE_ID = os.getenv("BANK_ACCOUNT_TABLE_ID", "bank_transaction_table")
_CHILD_ACCOUNT_TABLE_ID = os.getenv("CHILD_ACCOUNT_TABLE_ID", "child_account_table")
_ADULT_ACCOUNT_TABLE_ID = os.getenv("ADULT_ACCOUNT_TABLE_ID", "adult_account_table")
_FAMILY_TABLE_ID = os.getenv("USER_ACCOUNT_TABLE_ID", "family_table")
_STORE_TABLE_ID = os.getenv("STORE_TABLE_ID", "store_table")

AMQP_USER = os.getenv("AMQP_USER", 'guest')
AMQP_PW = os.getenv("AMQP_PW", 'guest')
AMQP_HOST = os.getenv("AMQP_HOST", '192.168.1.5')
AMQP_PORT = os.getenv("AMQP_PORT", 5672)

AMPQ_URL = os.getenv("AMPQ_URL", f"amqp://{AMQP_USER}:{AMQP_PW}@{AMQP_HOST}:{AMQP_PORT}")

_BANK_MANAGER_APP_QUEUE = os.getenv("BANK_MANAGER_APP_QUEUE", "bank_manager_worker_queue")
_BANK_MANAGER_WORKER_SQLITE_EVENT_STORE = os.getenv(
    "BANK_MANAGER_WORKER_SQLITE_EVENT_STORE",
    "_db/{}_bank_manager_worker_event_store.sqlite")

_STORE_MANAGER_APP_QUEUE = os.getenv("STORE_MANAGER_APP_QUEUE", "store_manager_worker_queue")
_STORE_MANAGER_WORKER_SQLLITE_EVENT_STORE = os.getenv(
    "STORE_MANAGER_WORKER_SQLLITE_EVENT_STORE",
    "_db/store_manager_event_store.sqllite"
)

_PERSISTENCE_WORKER_QUEUE = os.getenv("PERSISTENCE_WORKER_QUEUE", "persistence_worker_queue")
_PERSISTENCE_WORKER_SQLITE_EVENT_STORE = os.getenv(
    "PERSISTENCE_WORKER_SQLITE_EVENT_STORE",
    "{}/{}_persistence_worker_event_store.sqlite")

MONGO_HOST = os.getenv("MONGO_HOST", "192.168.1.5")
MONGO_PORT = os.getenv("MONGO_PORT", 27017)
_APP_DB = os.getenv("APP_DB", "BOE_MVP")
_BOE_DLQ_QUEUE = os.getenv("BOE_DLQ_QUEUE", "BOE_ERRORS")
_BOE_DLQ_EXCHANGE = os.getenv("BOE_DLQ_EXCHANGE", "BOE_ERROR_EXCHANGE")
_BOE_DLQ_DEFAULT_ROUTING_KEY = os.getenv("BOE_DLQ_DEFAULT_ROUTING_KEY", "BOE_EXCEPTIONS")

APP_DB = f'{STAGE}_{_APP_DB}'.upper()

BANK_ACCOUNT_TABLE = f'{STAGE}_{_BANK_ACCOUNT_TABLE_ID}'.upper()
BANK_TRANSACTION_TABLE = f'{STAGE}_{_BANK_TRANSACTION_TABLE_ID}'.upper()
CHILD_ACCOUNT_TABLE = f'{STAGE}_{_CHILD_ACCOUNT_TABLE_ID}'.upper()
ADULT_ACCOUNT_TABLE = f'{STAGE}_{_ADULT_ACCOUNT_TABLE_ID}'.upper()
FAMILY_TABLE = f'{STAGE}_{_FAMILY_TABLE_ID}'.upper()
STORE_TABLE = f'{STAGE}_{_STORE_TABLE_ID}'.upper()

BANK_MANAGER_WORKER_QUEUE = f'{STAGE}_{_BANK_MANAGER_APP_QUEUE}'.upper()
# BANK_MANAGER_WORKER_SQLITE_EVENT_STORE = _BANK_MANAGER_WORKER_SQLITE_EVENT_STORE.format(STAGE).upper()
BANK_MANAGER_WORKER_SQLITE_EVENT_STORE = _BANK_MANAGER_WORKER_SQLITE_EVENT_STORE.upper()

STORE_MANAGER_WORKER_QUEUE = f'{STAGE}_{_STORE_MANAGER_APP_QUEUE}'.upper()
PERSISTENCE_WORKER_QUEUE = f'{STAGE}_{_PERSISTENCE_WORKER_QUEUE}'.upper()
# PERSISTENCE_WORKER_SQLITE_EVENT_STORE = _PERSISTENCE_WORKER_SQLITE_EVENT_STORE.format(FILE_ROOT, STAGE).upper()
PERSISTENCE_WORKER_SQLITE_EVENT_STORE = _PERSISTENCE_WORKER_SQLITE_EVENT_STORE.upper()

SQLLITE_WORKER_EVENT_STORE = os.getenv("SQLLITE_WORKER_EVENT_STORE", "_db/workers_event_store")
STORE_MANAGER_WORKER_SQLLITE_EVENT_STORE = _STORE_MANAGER_WORKER_SQLLITE_EVENT_STORE.upper()

_NOTIFICATION_WORKER_QUEUE = os.getenv("NOTIFICATION_WORKER_QUEUE", 'notification_worker_queue')
NOTIFICATION_WORKER_QUEUE = f'{STAGE}_{_NOTIFICATION_WORKER_QUEUE}'.upper()

BOE_DLQ_QUEUE = f'{STAGE}_{_BOE_DLQ_QUEUE}'
BOE_DLQ_EXCHANGE = f'{STAGE}_{_BOE_DLQ_EXCHANGE}'
BOE_DLQ_DEFAULT_ROUTING_KEY = f'{STAGE}_{_BOE_DLQ_DEFAULT_ROUTING_KEY}'
