version: '3.1'

services:
  boe_api:
    image: cbaxter1988/boe_core
    environment:
      - STAGE=BETA

    command: python3 -m boe.api.boe_api
    ports:
      - 5000:5000

    env_file:
      - .env

  bank_manager_worker:
    image: cbaxter1988/boe_core
    environment:
      - BANK_MANAGER_WORKER_EVENT_STORE=event_store.sqllite
      - STAGE=BETA
    command: python3 -m boe.workers.bank_manager_worker
    env_file:
      - .env

  store_manager_worker:
    image: cbaxter1988/boe_core
    environment:
      - STORE_MANAGER_WORKER_EVENT_STORE=event_store.sqllite
      - STAGE=BETA
    command: python3 -m boe.workers.store_manager_worker
    env_file:
      - .env

  user_manager_worker:
    image: cbaxter1988/boe_core
    environment:
      - USER_MANAGER_WORKER_EVENT_STORE=event_store.sqllite
      - STAGE=BETA
    env_file:
      - .env

    command: python3 -m boe.workers.user_manager_worker

  influxdb:
    image: influxdb:latest
    ports:
      - '8086:8086'
    volumes:
      - influxdb-storage:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=boe_metrics
      - INFLUXDB_ADMIN_USER=boe_metric
      - INFLUXDB_ADMIN_PASSWORD=boe_metric

volumes:
  influxdb-storage: