version: '3.1'

services:

  env_builder:
    image: cbaxter1988/boe_core

    environment:
      - STAGE=${STAGE}

    command: python3 -m boe.workers.env_setup
    env_file:
      - .env

  auth_api:
    image: cbaxter1988/boe_core

    command: python3 -m boe.api.user_auth_api
    ports:
      - 9000:9000

    env_file:
      - .env

    environment:
      - STAGE=${STAGE}


  boe_api:
    image: cbaxter1988/boe_core

    command: python3 -m boe.api.core_api
    ports:
      - ${API_LISTEN_PORT}:${API_LISTEN_PORT}

    env_file:
      - .env

    environment:
      - STAGE=${STAGE}
      - API_LISTEN_PORT=${API_LISTEN_PORT}

  bank_manager_worker:
    image: cbaxter1988/boe_core
    environment:
      - BANK_MANAGER_WORKER_EVENT_STORE=event_store.sqllite
      - STAGE=${STAGE}

    command: python3 -m boe.workers.bank_manager_worker
    env_file:
      - .env


  store_manager_worker:
    image: cbaxter1988/boe_core
    environment:
      - STORE_MANAGER_WORKER_EVENT_STORE=event_store.sqllite
      - STAGE=${STAGE}
    command: python3 -m boe.workers.store_manager_worker
    env_file:
      - .env


  user_manager_worker:
    image: cbaxter1988/boe_core
    environment:
      - USER_MANAGER_WORKER_EVENT_STORE=event_store.sqllite
      - STAGE=${STAGE}

    env_file:
      - .env
    command: python3 -m boe.workers.user_manager_worker


  task_manager_worker:
    image: cbaxter1988/boe_core
    environment:
      - USER_MANAGER_WORKER_EVENT_STORE=event_store.sqllite
      - STAGE=${STAGE}
    env_file:
      - .env

    command: python3 -m boe.workers.task_manager_worker
