version: '3.1'

services:

  env_builder:
    image: cbaxter1988/boe_core

    command: python3 -m boe.workers.env_setup
    env_file:
      - .env

  boe_api:
    image: cbaxter1988/boe_core

    command: python3 -m boe.api.boe_api
    ports:
      - 5000:5000

    env_file:
      - .env

    depends_on:
      - env_builder

  bank_manager_worker:
    image: cbaxter1988/boe_core
    environment:
      - BANK_MANAGER_WORKER_EVENT_STORE=event_store.sqllite

    command: python3 -m boe.workers.bank_manager_worker
    env_file:
      - .env

    depends_on:
      - env_builder

  store_manager_worker:
    image: cbaxter1988/boe_core
    environment:
      - STORE_MANAGER_WORKER_EVENT_STORE=event_store.sqllite

    command: python3 -m boe.workers.store_manager_worker
    env_file:
      - .env
    depends_on:
      - env_builder

  user_manager_worker:
    image: cbaxter1988/boe_core
    environment:
      - USER_MANAGER_WORKER_EVENT_STORE=event_store.sqllite

    env_file:
      - .env
    command: python3 -m boe.workers.user_manager_worker
    depends_on:
      - env_builder
